[package]
name = "battleship"
version = "0.1.0"
authors = ["a1lu <a1lu@arcor.de>"]
edition = "2018"
license = "MIT"
license-file ="LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
